######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 12 13:55:50 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include
INCLUDEPATH += . include

# Input
HEADERS += main.h \
           shapture.h \
           include/dhcp.h \
           include/ospf.h \
           include/pack_dcp.h \
           include/rip.h
FORMS += ui.ui
SOURCES += main.cpp shapture.cpp
